"""An auditable local journey. Receipt bytes are evidence, never cloud authority.

Generation uses the production engine and its independent preservation oracle.
Execution uses a protected synthetic child process or an explicitly selected
pinned native OpenTofu output-only fixture. Its full semantic model does not
implement Microsoft Graph or provider import. Optional pinned Atmos execution
establishes configuration comparison only.
"""
from __future__ import annotations
import hashlib
import copy
import os
from pathlib import Path
import re
import secrets
import tempfile
from uuid import uuid4

from . import engine, runner, workflow
from .io import AppError, canonical, digest, file_sha, load_json, write_json, sync_directory, mkdir_durable

VERSION = 'journey/1.0'
STAGES = ('discovery', 'target', 'inventory', 'selection', 'preservation', 'mapping',
          'ownership', 'atmos', 'generation', 'validation', 'adoption', 'plan',
          'approval', 'execute', 'reconcile', 'convergence', 'handoff')
LIVE_BLOCKERS = ('provider_not_qualified', 'authenticated_target_missing',
                 'state_backend_not_observed', 'single_writer_not_verified',
                 'protected_cloud_approval_unavailable', 'cloud_executor_unavailable')
COMMANDS = {'generation': 'generate', 'plan': 'plan', 'approval': 'approve',
            'execute': 'execute', 'reconcile': 'reconcile', 'handoff': 'finish'}
DESCRIPTIONS = {
    'discovery': ('repository files', 'repository discovery', 'Reread literal repository sources.'),
    'target': ('context and capture identity', 'target intent evidence', 'Reobserve target; authenticated identity is still required for live use.'),
    'inventory': ('complete capture bytes', 'immutable object inventory', 'Refresh capture; do not infer missing collections as empty.'),
    'selection': ('inventory and UUID intent', 'selected identity set', 'Reselect immutable UUIDs; preserve prior output.'),
    'preservation': ('capture and independent normalization oracle', 'preservation comparison', 'Correct source evidence before regeneration.'),
    'mapping': ('normalized objects and qualification gates', 'mapping and blocker review', 'Preserve unsupported content and inactive candidate gate.'),
    'ownership': ('source ownership declarations', 'unknown ownership assessment', 'Observe genuine backend ownership before live adoption.'),
    'atmos': ('literal repository configuration and target intent', 'Atmos placement review', 'Resolve source configuration; no native Atmos execution is implied.'),
    'generation': ('source context and selection', 'new local proposal tree', 'Reconcile existing bytes; never replay an uncertain write.'),
    'validation': ('current source and every generated byte', 'independent proposal validation', 'Regenerate into a fresh output after edits.'),
    'adoption': ('validated proposal and selected UUIDs', 'simulation import proposal', 'Review identity binding; live import remains unavailable.'),
    'plan': ('adoption proposal and selected protected local executor', 'saved local plan', 'Replan when any bound byte changes.'),
    'approval': ('saved plan bytes and current user intent', 'local approval review receipt', 'Resume requires fresh in-process approval; saved JSON grants nothing.'),
    'execute': ('saved plan and in-process simulation grant', 'bounded child-process state and operation ledger', 'Reconcile uncertain outcomes; never automatically retry.'),
    'reconcile': ('operation ledger and independently observed local state', 'local outcome classification', 'A desired observation does not establish a cloud operation.'),
    'convergence': ('current local state and fresh desired model', 'second comparison with no changes', 'Investigate divergence; do not auto-apply again.'),
    'handoff': ('verified receipt chain and remaining gates', 'local handoff summary', 'Reconstruct the chain and qualify live gates separately.'),
}


def action_contract():
    return {'schema_version': VERSION, 'closed_vocabulary': True, 'actions': [
        {'id': stage, 'requires': list(STAGES[:index]), 'reads': [DESCRIPTIONS[stage][0]],
         'writes': [DESCRIPTIONS[stage][1], 'local receipt'],
         'authority': 'in_process_local_executor_grant' if stage == 'execute' else 'local_only',
         'cloud_authority': False, 'recovery': DESCRIPTIONS[stage][2],
         'invalidates': list(STAGES[index + 1:])}
        for index, stage in enumerate(STAGES)]}


def semantic_contract():
    """Closed meanings used by receipt reconstruction and public reporting."""
    return {'schema_version': VERSION, 'evidence_classes': {
        'local_evidence_only': {'establishes': ['local byte consistency', 'source-derived proposal preservation'],
                                'does_not_establish': ['authenticated tenant', 'backend ownership', 'native provider behavior']},
        'synthetic_local_process_only': {'establishes': ['bounded child-process execution', 'full semantic model comparison', 'modeled service readback'],
                                         'does_not_establish': ['Intune import', 'Microsoft Graph changes', 'native Atmos execution', 'provider convergence']},
        'native_local_opentofu_only': {'establishes': ['pinned native output-only saved-plan execution when explicitly selected', 'actual no-change second plan'],
                                      'does_not_establish': ['native Intune resource import', 'provider qualification', 'tenant mutation']},
        'live': {'establishes': [], 'does_not_establish': ['available live execution capability']}},
        'stages': {stage: {'evidence_class': 'synthetic_local_process_only' if STAGES.index(stage) >= STAGES.index('plan') else 'local_evidence_only',
                           'optional_evidence_class': 'native_local_opentofu_only' if STAGES.index(stage) >= STAGES.index('plan') else None,
                           'depends_on': list(STAGES[:STAGES.index(stage)]), 'cloud_authority': False}
                   for stage in STAGES},
        'live_readiness_requires': list(LIVE_BLOCKERS), 'saved_session_is_authority': False}


def _safe(path):
    return workflow._safe(path)


def _root(session):
    return _safe(str(session) + '.journey')


def _receipt_path(session, stage):
    return _safe(_root(session) / 'receipts' / (stage + '.json'))


def _validate_paths(session, state):
    root = _root(session)
    paths = {name: _safe(value) for name, value in state['paths'].items()}
    protected = [session, root, paths['input'], paths['context']]
    output = paths['output']
    if any(output == p or output in p.parents for p in protected):
        raise AppError('journey_path_conflict', 'Output must not contain source or session evidence.')
    if any(p == session or p == root or root in p.parents or p in root.parents for p in (paths['input'], paths['context'])):
        raise AppError('journey_path_conflict', 'Source and session evidence must be separate.')
    if state['repository'] is not None and (_safe(state['repository']) == root or root in _safe(state['repository']).parents):
        raise AppError('journey_path_conflict', 'Repository must be outside journey evidence.')
    return root


def _load(session):
    state = load_json(_safe(session))
    keys = {'schema_version', 'paths', 'repository', 'target', 'selected_ids', 'mode', 'lifecycle', 'in_flight', 'completed'}
    if (not isinstance(state, dict) or not keys <= set(state) <= keys | {'atmos_executable', 'tofu_executable'}
            or state['schema_version'] != VERSION):
        raise AppError('journey_invalid_session', 'Use a separate session for the full journey.')
    if state['mode'] not in ('simulation', 'live') or state['lifecycle'] not in ('active', 'suspended', 'cancelled', 'complete_simulation'):
        raise AppError('journey_invalid_session', 'Unsupported journey mode or lifecycle.')
    if not isinstance(state['paths'], dict) or set(state['paths']) != {'input', 'context', 'output'} or any(not isinstance(p, str) or not p or len(p) > 4096 for p in state['paths'].values()):
        raise AppError('journey_invalid_session', 'Bounded source, context and output paths are required.')
    if state['repository'] is not None and (not isinstance(state['repository'], str) or len(state['repository']) > 4096):
        raise AppError('journey_invalid_session', 'Invalid repository path.')
    if not isinstance(state['target'], dict) or not set(state['target']) <= {'stack', 'component'} or any(not isinstance(v, str) or not re.fullmatch(r'[A-Za-z0-9_./-]{1,256}', v) for v in state['target'].values()):
        raise AppError('journey_invalid_session', 'Target intent must be literal.')
    state['selected_ids'] = _selected_ids(state['selected_ids'], allow_empty=True)
    if state.get('atmos_executable') is not None:
        if type(state['atmos_executable']) is not str or len(state['atmos_executable']) > 4096 or state['repository'] is None:
            raise AppError('journey_atmos_configuration', 'Native Atmos needs an explicit executable and repository.')
        _safe(state['atmos_executable'])
    if state.get('tofu_executable') is not None:
        if type(state['tofu_executable']) is not str or len(state['tofu_executable']) > 4096:
            raise AppError('journey_tofu_configuration', 'Native local OpenTofu needs an explicit pinned executable.')
        _safe(state['tofu_executable'])
    if state['in_flight'] not in (None, 'generation', 'execute') or not isinstance(state['completed'], list):
        raise AppError('journey_invalid_session', 'Invalid operation checkpoint.')
    _validate_paths(session, state)
    return state


def _selected_ids(values, *, allow_empty=False):
    ids = workflow._ids(values, allow_empty=allow_empty)
    if len(ids) > 8:
        raise AppError('journey_selection_limit', 'The connected synthetic journey supports at most eight selected policies; inventory may contain more.')
    return ids


def _work_state(state):
    return {'paths': state['paths'], 'repository': state['repository'], 'target': state['target'],
            'selected_ids': state['selected_ids'], 'cohort': {'ring': 'ring0', 'group_ids': []}}


def _selected_source(source, policy_id):
    """Project one synthetic selection without weakening single-policy parsing.

    The original complete capture remains the inventory/fingerprint authority.
    Only known collections owned by other immutable IDs are excluded from this
    specific engine invocation; selected content and the inventory stay exact.
    """
    if source.get('synthetic') is not True: return source
    selected = copy.deepcopy(source)
    owners = {row.get('id') for collection in source['collections'] if collection.get('kind') == 'policies'
              for page in collection.get('pages', []) for row in page.get('body', {}).get('value', [])}
    selected['collections'] = [row for row in selected['collections']
                               if not (row.get('kind') in ('settings', 'assignments')
                                       and row.get('owner_id') in owners and row.get('owner_id') != policy_id)]
    selected['ownership'] = [row for row in selected.get('ownership', [])
                             if row.get('object_id') == policy_id or row.get('object_id') not in owners]
    return selected


def _inspect_selected(state, context, source, policy_id, *, verify=False):
    selected = _selected_source(source, policy_id)
    with tempfile.TemporaryDirectory(prefix='intune-journey-selection-') as temporary:
        context_path = Path(temporary) / 'context.json'
        write_json(context_path, dict(context, selected_policy_id=policy_id))
        if selected == source: source_path = state['paths']['input']
        else:
            source_path = Path(temporary) / 'capture.json'; write_json(source_path, selected)
        if verify: return engine.verify_project(source_path, context_path, Path(state['paths']['output']) / policy_id)
        return engine.inspect_source(source_path, context_path)


def _generation_evidence(state, observed):
    output = _safe(state['paths']['output'])
    if not output.is_dir() or {p.name for p in output.iterdir()} != set(state['selected_ids']):
        raise AppError('workflow_output_closure', 'Generated cohort differs from the selected immutable identities.')
    results = {}
    for policy_id in state['selected_ids']:
        result = _inspect_selected(state, observed['context'], observed['raw_capture'], policy_id, verify=True)
        results[policy_id] = {'manifest_sha256': result['manifest_sha256'], 'file_count': result['file_count'],
                             'selection_source_sha256': digest(_selected_source(observed['raw_capture'], policy_id))}
    return {'policies': results, 'target_digest': observed['fingerprints']['target'],
            'output_digest': observed['fingerprints']['output'],
            'complete_inventory_sha256': observed['fingerprints']['source']}


def _observe(session, state):
    working = _work_state(state)
    before = {key: file_sha(_safe(state['paths'][key])) for key in ('input', 'context')}
    # Synthetic generation may inspect a repository, but cannot claim that the
    # reference generator is a qualified mapping for an arbitrary repository.
    source = load_json(_safe(state['paths']['input']))
    if not isinstance(source, dict):
        raise AppError('invalid_capture', 'Capture must be a versioned JSON object.')
    if source.get('synthetic') is True:
        working['repository'] = None
    # Inventory/context validation operates on the complete capture once.
    # Selection-specific normalization below uses explicit single-policy views;
    # repeating the workflow's unscoped normalizations is both redundant and
    # outside that engine's deliberate single-selection input contract.
    observed = workflow._observe(session, dict(working, selected_ids=[]))
    if not set(state['selected_ids']) <= set(observed['observed_ids']):
        raise AppError('workflow_selection_missing', 'A selected policy is absent from the complete inventory.')
    observed['fingerprints']['selection'] = digest(state['selected_ids'])
    context = observed['context']
    if (workflow._uuid(source.get('tenant_id')) != workflow._uuid(context.get('tenant_id'))
            or source.get('cloud') != context.get('cloud')
            or ('source_is_synthetic' in context and source.get('synthetic') is not context['source_is_synthetic'])):
        raise AppError('journey_target_mismatch', 'Capture identity and target intent do not agree.')
    observed['inspections'] = {key: _inspect_selected(state, observed['context'], source, key) for key in state['selected_ids']}
    observed['discovery'] = {'mode': 'no_repository_supplied', 'assurance': 'local_context_only'}
    if state['repository'] is not None:
        from .repository import discover_repository
        found = discover_repository(_safe(state['repository']))
        observed['discovery'] = {'mode': 'literal_repository', 'status': found.get('status'), 'discovery_sha256': digest(found)}
    if before != {key: file_sha(_safe(state['paths'][key])) for key in ('input', 'context')}:
        raise AppError('journey_inputs_changed', 'Source or context changed during independent observation.')
    observed['raw_capture'] = source
    return observed


def _desired(state, observed):
    # The exact saved plan now carries every supported semantic field rather
    # than just opaque normalization hashes. The engine's independent oracle
    # still validates generation; synthetic raw pages supply another separate
    # projection before an executable model is admitted.
    objects = {key: value['normalized'].get('desired', value['normalized'].get('configuration'))
               for key, value in observed['inspections'].items()}
    semantic = {'schema_version': 'intune-semantic-estate/1.0',
                'tenant_id': observed['context']['tenant_id'], 'cloud': observed['context']['cloud'],
                'objects': objects}
    if observed['raw_capture'].get('synthetic') is True:
        from .modeled_service import project_capture, compare_semantics
        expected = project_capture(observed['raw_capture'], state['selected_ids'])
        if compare_semantics(expected, semantic):
            raise AppError('journey_semantic_projection_mismatch', 'The complete raw capture does not match the planned semantic estate.')
    return {'policies': semantic,
            'source_sha256': observed['fingerprints']['source'],
            'target_sha256': observed['fingerprints']['target']}


def _service_outcome(session, state, observed):
    """Reconstruct model readback; a receipt flag never proves preservation."""
    if observed['raw_capture'].get('synthetic') is not True:
        return {'scope': 'not_available_for_non_synthetic_capture', 'verified': False}
    from .modeled_service import ModeledService, project_capture, compare_semantics
    expected = project_capture(observed['raw_capture'], state['selected_ids'])
    snapshot = ModeledService(_root(session) / 'modeled-service').snapshot()
    readback = load_json(_safe(_root(session) / 'modeled-readback.json'))
    if (type(readback) is not dict or set(readback) != {'estate', 'revision', 'request_count'}
            or snapshot['source_sha256'] != digest(observed['raw_capture'])
            or compare_semantics(expected, snapshot['initial'])
            or compare_semantics(expected, snapshot['current'])
            or compare_semantics(expected, readback['estate'])
            or readback['revision'] != snapshot['revision']
            or readback['request_count'] != len(snapshot['requests'])
            or any(row['method'] != 'GET' or row['status'] != 200 or row['mutation_committed'] for row in snapshot['requests'])):
        raise AppError('journey_modeled_service_diverged', 'Synthetic service readback no longer preserves the pre-adoption estate.')
    return {'scope': 'stateful_synthetic_service_only', 'verified': True,
            'immutable_ids': sorted(expected['objects']), 'revision': snapshot['revision'],
            'request_count': len(snapshot['requests']), 'estate_sha256': digest(readback['estate']),
            'requests_sha256': digest(snapshot['requests']), 'remote_mutations': 0}


def _native(session):
    from .protected import SyntheticExecutor, NativeLocalExecutor, _sha
    locator = _load(session).get('tofu_executable')
    cls = NativeLocalExecutor if locator is not None else SyntheticExecutor
    executor = cls(_root(session) / 'synthetic-executor')
    if locator is not None and _sha(_safe(locator)) != executor.manifest['executable_sha256']:
        raise AppError('journey_tool_changed', 'Selected OpenTofu executable differs from the bound plan; review and replan.')
    return executor


def _request(session, state, observed):
    from .protected import inspect_executor, validate_native_operation
    path = _safe(_root(session) / 'native-request.json')
    request = load_json(path)
    expected = digest(_desired(state, observed))
    executor = _native(session)
    validate_native_operation(request, executor=executor, require_fresh=False, require_state=False)
    snapshot = inspect_executor(executor)
    if request.get('bindings', {}).get('desired_value_sha256') != expected or snapshot.get('desired_value_sha256') != expected:
        raise AppError('journey_plan_changed', 'Saved simulation plan no longer matches the current source and target.')
    if observed['raw_capture'].get('synthetic') is True:
        from .modeled_service import ModeledService, project_capture, compare_semantics
        service = ModeledService(_root(session) / 'modeled-service').snapshot()
        truth = project_capture(observed['raw_capture'], state['selected_ids'])
        if (service['source_sha256'] != digest(observed['raw_capture'])
                or compare_semantics(truth, service['initial'])
                or compare_semantics(truth, service['current'])):
            raise AppError('journey_modeled_service_diverged', 'Synthetic service changed after inventory; refresh and review before adoption.')
    return request


def _simulation_outcome(session, state, observed):
    from .protected import read_native_operation, reconcile_native_operation, inspect_executor
    request = _request(session, state, observed)
    saved = load_json(_safe(_root(session) / 'native-result.json'))
    operation = read_native_operation(request['operation_id'], _root(session) / 'operations')
    observation = reconcile_native_operation(request['operation_id'], _root(session) / 'operations', executor=_native(session))
    snapshot = inspect_executor(_native(session))
    if (saved.get('status') != 'succeeded_verified' or operation.get('status') != 'succeeded_verified'
            or operation.get('request') != request or saved.get('operation_id') != request['operation_id']
            or saved.get('receipt_sha256') != operation.get('receipt_sha256')
            or observation.get('classification') != 'desired_state_observed'
            or snapshot.get('value_sha256') != digest(_desired(state, observed))):
        raise AppError('journey_reconciliation_required', 'Synthetic operation or local state no longer verifies.')
    return {'operation_id': request['operation_id'], 'receipt_sha256': saved['receipt_sha256'],
            'state_sha256': snapshot['state_sha256'], 'value_sha256': snapshot['value_sha256'],
            'classification': observation['classification'], 'assurance': snapshot['mode'],
            'service_readback': _service_outcome(session, state, observed)}


def _payload(stage, session, state, observed, cache=None):
    # One read-only reconstruction may share identical derivations. The cache is
    # never retained across prompts, dispatch, edits, or reconstruction calls.
    cache = {} if cache is None else cache
    key = {'validation': 'generation', 'reconcile': 'execute'}.get(stage, stage)
    if key not in cache:
        cache[key] = _derive_payload(key, session, state, observed, cache)
    return cache[key]


def _derive_payload(stage, session, state, observed, cache):
    context = observed['context']; inputs = observed['fingerprints']
    if stage == 'discovery': return observed['discovery']
    if stage == 'target':
        return {'tenant_id': context['tenant_id'], 'cloud': context.get('cloud'),
                'tenant_assurance': 'source_asserted', 'context_sha256': file_sha(_safe(state['paths']['context'])),
                'target_intent_sha256': inputs['target'], 'authenticated_target': False}
    if stage == 'inventory': return observed['payloads']['inventory']
    if stage == 'selection':
        if not state['selected_ids']: raise AppError('journey_selection_required', 'Select one or more observed UUIDs.')
        return {'selected_ids': state['selected_ids'], 'source_sha256': inputs['source']}
    if stage == 'preservation':
        return {'policies': {key: {'normalized_sha256': digest(value['normalized']),
                                   'independent_preservation_verified': value['preservation_verified']}
                             for key, value in observed['inspections'].items()}}
    if stage == 'mapping':
        return {'policies': {key: {'source_mode': value['source_mode'], 'status': value['status'],
                                   'candidate_mapping_complete': value['normalized'].get('candidate_mapping_complete', value['status'] == 'ready'),
                                   'blocker_codes': sorted({b['code'] for b in value['blockers']})}
                             for key, value in observed['inspections'].items()}, 'live_provider_qualified': False}
    if stage == 'ownership': return {'status': 'unknown', 'writer_qualified': False, 'backend_observed': False}
    if stage == 'atmos':
        if state.get('atmos_executable') is not None:
            from .journey_native_atmos import reconstruct
            native = reconstruct(state['repository'], context['stack'], context['component'],
                                 state['atmos_executable'], _root(session) / 'native-atmos.json')
            return {'stack': context.get('stack'), 'component': context.get('component'),
                    'repository': observed['discovery'], 'target_intent_sha256': inputs['target'],
                    'native_atmos_executed': True, 'assurance': 'native_configuration_only',
                    'native_comparison': native}
        return {'stack': context.get('stack'), 'component': context.get('component'),
                'repository': observed['discovery'], 'target_intent_sha256': inputs['target'],
                'native_atmos_executed': False, 'assurance': 'literal_source_or_context_intent'}
    if stage in ('generation', 'validation'):
        generated = _generation_evidence(state, observed)
        return dict(generated, independent_preservation_verified=True, native_provider_validated=False)
    if stage == 'adoption':
        return {'kind': 'simulation_import_preview', 'objects': [{'policy_id': key, 'normalized_sha256': digest(value['normalized'])}
                for key, value in observed['inspections'].items()], 'live_import_allowed': False}
    if stage == 'plan':
        request = _request(session, state, observed)
        return {'kind': 'native_local_output_only_saved_plan' if state.get('tofu_executable') else 'bounded_synthetic_saved_plan', 'desired_value_sha256': digest(_desired(state, observed)),
                'request_sha256': file_sha(_safe(_root(session) / 'native-request.json')),
                'operation_id': request['operation_id'], 'policy_ids': state['selected_ids'],
                'native_tool_source': ({'path': state['tofu_executable'], 'sha256': _native(session).manifest['executable_sha256']}
                                       if state.get('tofu_executable') else None),
                'provider_plan': False, 'cloud_changes': 0,
                'semantic_fields': ['immutable_ids', 'name', 'description', 'platforms', 'technologies',
                                    'role_scope_tag_ids', 'settings', 'assignments'],
                'stateful_service_model': observed['raw_capture'].get('synthetic') is True}
    if stage == 'approval':
        return {'review_sha256': digest(_payload('plan', session, state, observed, cache)),
                'grant_persisted': False, 'scope': 'simulation_only', 'cloud_authority': False}
    if stage in ('execute', 'reconcile'):
        return _simulation_outcome(session, state, observed)
    if stage == 'convergence':
        outcome = _payload('execute', session, state, observed, cache)
        result = {'state_sha256': outcome['state_sha256'], 'desired_value_sha256': digest(_desired(state, observed)),
                  'changes': [], 'converged': True, 'scope': 'synthetic_full_semantic_state_only',
                  'service_readback': outcome['service_readback']}
        if state.get('tofu_executable') is not None:
            from .protected import reconstruct_native_convergence
            result['native_second_plan'] = reconstruct_native_convergence(_native(session), _request(session, state, observed),
                                            load_json(_safe(_root(session) / 'native-convergence.json')))
            result['scope'] = 'native_local_output_only_and_synthetic_service'
        return result
    return {'scope': 'local_simulation_completed', 'selected_ids': state['selected_ids'],
            'generation_sha256': digest(_payload('generation', session, state, observed, cache)),
            'convergence_sha256': digest(_payload('convergence', session, state, observed, cache)),
            'live_ready': False, 'live_blockers': list(LIVE_BLOCKERS),
            'provider_or_atmos_native_execution': state.get('atmos_executable') is not None,
            'native_atmos_configuration_only': state.get('atmos_executable') is not None,
            'native_opentofu_output_only': state.get('tofu_executable') is not None,
            'native_provider_execution': False, 'cloud_execution': False}


def _receipt(stage, session, state, observed, dependencies, cache=None):
    return {'schema_version': VERSION, 'stage': stage, 'mode': state['mode'],
            'assurance': ('native_local_opentofu_only' if state.get('tofu_executable') else 'synthetic_local_process_only') if STAGES.index(stage) >= STAGES.index('plan') else 'local_evidence_only',
            'dependencies': dependencies.copy(), 'payload': _payload(stage, session, state, observed, cache),
            'cloud_authority': False}


def _progress(session, state, observed):
    verified = []; dependencies = {}; invalid = None; cache = {}
    for stage in STAGES:
        try:
            if state['mode'] == 'live' and STAGES.index(stage) >= STAGES.index('plan'):
                break
            path = _receipt_path(session, stage)
            if not path.exists(): break
            if load_json(path) != _receipt(stage, session, state, observed, dependencies, cache):
                invalid = stage; break
            dependencies[stage] = file_sha(path); verified.append(stage)
        except (AppError, OSError, ValueError, KeyError, TypeError, ImportError):
            invalid = stage; break
    next_state = STAGES[len(verified)] if len(verified) < len(STAGES) else 'complete_simulation'
    if state['in_flight'] is not None: next_state = 'recovery_required'
    return {'schema_version': VERSION, 'next_state': next_state, 'verified_completed': verified,
            'external_verified_completed': [], 'receipt_dependencies': dependencies,
            'invalid_at': invalid, 'mode': state['mode'], 'execution_authorized': False,
            'live_ready': False, 'live_blockers': list(LIVE_BLOCKERS)}


def reconstruct_progress(session_path):
    session = _safe(session_path); state = _load(session)
    return _progress(session, state, _observe(session, state))


def check_action(session_path, action):
    if action not in STAGES:
        return {'allowed': False, 'reason': 'unknown_action', 'cloud_authority': False}
    progress = reconstruct_progress(session_path)
    contract = action_contract()['actions'][STAGES.index(action)]
    allowed = progress['next_state'] == action
    if progress['mode'] == 'live' and STAGES.index(action) >= STAGES.index('plan'): allowed = False
    # A read-only JSON preview cannot establish possession of a process-local
    # capability. Only the controller and protected dispatcher can check it.
    if action == 'execute':
        return {'allowed': False, 'reason': 'in_process_grant_required',
                'prerequisites_verified': progress['next_state'] == action,
                'contract': contract, 'cloud_authority': False}
    return {'allowed': allowed, 'reason': 'prerequisites_verified' if allowed else 'prerequisites_or_authority_missing',
            'contract': contract, 'cloud_authority': False}


def _checkpoint(session, state, observed, stage, guard):
    guard(); current = _progress(session, state, observed)
    expected = STAGES[len(current['verified_completed'])] if len(current['verified_completed']) < len(STAGES) else None
    if expected != stage:
        raise AppError('journey_prerequisites_missing', 'Stage prerequisites do not verify from current bytes.')
    write_json(_receipt_path(session, stage), _receipt(stage, session, state, observed, current['receipt_dependencies']))


def _invalidate(session, start):
    # Preserve old receipts without letting them supply current dependencies.
    archive = _safe(_root(session) / 'history' / uuid4().hex)
    for stage in STAGES[STAGES.index(start):]:
        path = _root(session) / 'receipts' / (stage + '.json')
        if path.exists() or path.is_symlink():
            _safe(path); mkdir_durable(archive)
            path.rename(archive / path.name)
            sync_directory(path.parent); sync_directory(archive)


def _generate(session, state, observed, guard):
    output = _safe(state['paths']['output'])
    if output.exists(): raise AppError('journey_output_conflict', 'Preserve existing output and choose a new output path.')
    state['in_flight'] = 'generation'; write_json(session, state)
    for key in state['selected_ids']:
        guard(); context = _root(session) / 'contexts' / (key + '.json')
        write_json(context, dict(observed['context'], selected_policy_id=key))
        selected = _selected_source(observed['raw_capture'], key)
        source_path = state['paths']['input']
        if selected != observed['raw_capture']:
            source_path = _root(session) / 'captures' / (key + '.json'); write_json(source_path, selected)
        result = runner.run('generate', {'input': str(source_path), 'context': str(context),
                                        'output': str(output / key)}, _root(session) / 'attempts')
        if result.get('status') != 'succeeded_verified':
            raise AppError('journey_generation_unknown', 'Preserve output; independently reconcile before retry.')
    fresh = _observe(session, state)
    if fresh['fingerprints'] != observed['fingerprints']:
        raise AppError('journey_inputs_changed', 'Source or target changed during generation.')
    _checkpoint(session, state, fresh, 'generation', guard)
    state['in_flight'] = None; write_json(session, state)


def _prepare_plan(session, state, observed):
    if state['mode'] != 'simulation': raise AppError('journey_live_blocked', 'Live readiness gates are not qualified.')
    if any(not value['normalized'].get('candidate_mapping_complete', value['status'] == 'ready') for value in observed['inspections'].values()):
        raise AppError('journey_mapping_incomplete', 'Unsupported mapping cannot enter the executable simulation.')
    from .protected import create_synthetic_executor, create_native_local_executor, prepare_native_operation
    location = _safe(_root(session) / 'synthetic-executor')
    if location.exists():
        # Replanning preserves earlier process evidence in a separate directory.
        archive = _safe(_root(session) / 'history' / uuid4().hex); mkdir_durable(archive)
        location.rename(archive / 'synthetic-executor')
        sync_directory(location.parent); sync_directory(archive)
    if state.get('tofu_executable') is not None:
        executor = create_native_local_executor(location, executable=state['tofu_executable'],
                                               initial_value={}, desired_value=_desired(state, observed))
    else:
        executor = create_synthetic_executor(location, initial_value={}, desired_value=_desired(state, observed))
    if observed['raw_capture'].get('synthetic') is True:
        from .modeled_service import ModeledService
        service_path = _safe(_root(session) / 'modeled-service')
        if service_path.exists():
            archive = _safe(_root(session) / 'history' / uuid4().hex); mkdir_durable(archive)
            service_path.rename(archive / 'modeled-service')
            sync_directory(service_path.parent); sync_directory(archive)
        service = ModeledService.create(service_path, observed['raw_capture'], state['selected_ids'])
        # Actual modeled requests establish the pre-adoption readback. They do
        # not invoke HTTP, Graph, native providers, or any live mutation.
        service.readback(tenant_id=observed['context']['tenant_id'])
    write_json(_root(session) / 'native-request.json', prepare_native_operation(executor, ttl_seconds=300))


def _readback_service(session, state, observed):
    if observed['raw_capture'].get('synthetic') is not True: return
    from .modeled_service import ModeledService
    service = ModeledService(_root(session) / 'modeled-service')
    estate = service.readback(tenant_id=observed['context']['tenant_id'])
    snapshot = service.snapshot()
    write_json(_root(session) / 'modeled-readback.json', {'estate': estate,
               'revision': snapshot['revision'], 'request_count': len(snapshot['requests'])})


def _edit(session, state, argument):
    field, _, value = argument.partition(' ')
    if field in ('input', 'context', 'output') and value:
        candidate = dict(state, paths=dict(state['paths'], **{field: str(_safe(value))}))
        _validate_paths(session, candidate); state['paths'] = candidate['paths']
        start = {'input': 'inventory', 'context': 'target', 'output': 'generation'}[field]
    elif field in ('stack', 'component') and re.fullmatch(r'[A-Za-z0-9_./-]{1,256}', value):
        state['target'][field] = value; start = 'target'
    elif field == 'selection':
        state['selected_ids'] = _selected_ids([item.strip() for item in value.split(',')]); start = 'selection'
    else: raise AppError('journey_invalid_edit', 'Use input, context, output, stack, component or selection.')
    _invalidate(session, start)


def _run(session, state, fresh, input_fn, output_fn, guard):
    root = _validate_paths(session, state)
    if fresh:
        if root.exists(): raise AppError('journey_evidence_conflict', 'Preserve existing evidence and choose a fresh session.')
        mkdir_durable(root); write_json(session, state)
    # A persisted approval cannot recreate an in-process execution capability.
    if not state['in_flight'] and not (_root(session) / 'receipts/execute.json').exists():
        _invalidate(session, 'approval')
    approval = None
    observed_once = False
    def unavailable(error):
        return {'schema_version': VERSION, 'next_state': 'observation_required',
                'verified_completed': [], 'external_verified_completed': [],
                'receipt_dependencies': {}, 'invalid_at': 'observation',
                'error': getattr(error, 'code', 'local_observation_failed'),
                'mode': state['mode'], 'execution_authorized': False,
                'live_ready': False, 'live_blockers': list(LIVE_BLOCKERS)}
    def finish(status):
        guard()
        if status != 'complete_simulation' and state['in_flight'] is None and not (_root(session) / 'receipts/execute.json').exists():
            _invalidate(session, 'approval')
        if state['lifecycle'] != 'cancelled' or status != 'suspended': state['lifecycle'] = status
        try: progress = _progress(session, state, _observe(session, state))
        except (AppError, OSError, ValueError, ImportError) as error:
            progress = unavailable(error)
        state['completed'] = progress['verified_completed']; write_json(session, state)
        return dict(progress, status=status, step=progress['next_state'], session=str(session))
    try:
        while True:
            guard()
            try:
                observed = _observe(session, state); observed_once = True
            except (AppError, OSError, ValueError) as error:
                if fresh and not observed_once: raise
                approval = None
                if state['in_flight'] is None: _invalidate(session, 'approval')
                output_fn('Source or target evidence is unavailable: ' + getattr(error, 'code', 'local_observation_failed'))
                output_fn('Preserved prior artifacts. Restore the original evidence, or use edit input PATH / edit context PATH; no operation is authorized.')
                answer = input_fn('Journey [edit FIELD VALUE/resume/save/cancel]: ').strip()
                if len(answer) > 8192: raise AppError('journey_input_limit', 'Command exceeds bounded input limits.')
                command, _, argument = answer.partition(' '); command = command.lower(); guard()
                if command in ('save', 'cancel'): return finish('suspended' if command == 'save' else 'cancelled')
                if state['in_flight'] is not None:
                    output_fn('An uncertain operation requires the original source and target; edits are blocked until readback can reconcile it.')
                elif state['lifecycle'] == 'cancelled':
                    if command == 'resume': state['lifecycle'] = 'active'
                    else: output_fn('Cancelled: enter resume before changing evidence.')
                elif command == 'edit':
                    try: _edit(session, state, argument)
                    except (AppError, OSError, ValueError) as edit_error:
                        output_fn('Evidence edit stopped: ' + getattr(edit_error, 'code', 'local_operation_failed'))
                else: output_fn('Restore evidence, edit its path, or save/cancel this session.')
                write_json(session, state); continue
            progress = _progress(session, state, observed)
            step = progress['next_state']
            output_fn('Journey ' + step + ' | local ' + str(len(progress['verified_completed'])) + '/' + str(len(STAGES)) + '; live gates remain blocked.')
            if step == 'selection': output_fn('Observed policy UUIDs: ' + ', '.join(observed['observed_ids']))
            if step == 'mapping': output_fn('Mapping review: ' + str(_payload('mapping', session, state, observed)))
            output_fn('Action reads/writes and recovery: ' + (str(action_contract()['actions'][STAGES.index(step)]) if step in STAGES else 'Review completed evidence or reconcile an uncertain local operation.'))
            answer = input_fn('Journey [continue/UUIDs/generate/plan/approve/execute/reconcile/finish/back STAGE/edit FIELD VALUE/resume/save/cancel]: ').strip()
            if len(answer) > 8192: raise AppError('journey_input_limit', 'Command exceeds bounded input limits.')
            guard(); command, _, argument = answer.partition(' '); command = command.lower()
            if command in ('save', 'cancel'): return finish('suspended' if command == 'save' else 'cancelled')
            if state['lifecycle'] == 'cancelled':
                if command == 'resume': state['lifecycle'] = 'active'; write_json(session, state)
                else: output_fn('Cancelled: enter resume before another local action.')
                continue
            try:
                if state['in_flight']:
                    if command != 'reconcile':
                        output_fn('Unknown local outcome: reconcile; no write replay is available.'); continue
                    output_fn('Working: reconstructing the uncertain outcome from durable evidence; no operation replay.')
                    if state['in_flight'] == 'generation':
                        _generation_evidence(state, observed)
                        _checkpoint(session, state, observed, 'generation', guard)
                    else:
                        _readback_service(session, state, observed)
                        _simulation_outcome(session, state, observed)
                        _checkpoint(session, state, observed, 'execute', guard)
                    state['in_flight'] = None
                elif command == 'back' and argument in STAGES:
                    _invalidate(session, argument); approval = None
                elif command == 'edit':
                    _edit(session, state, argument); approval = None
                elif step == 'complete_simulation':
                    if command == 'finish': return finish('complete_simulation')
                    output_fn('Completed; inspect evidence, back STAGE, edit, or save.')
                elif step == 'selection':
                    state['selected_ids'] = _selected_ids([item.strip() for item in answer.split(',')])
                    output_fn('Working: verifying the selected identities and preservation evidence.')
                    observed = _observe(session, state); _checkpoint(session, state, observed, step, guard)
                elif command == COMMANDS.get(step, 'continue'):
                    output_fn('Working: ' + step + '; rechecking current evidence and protected operation constraints.')
                    fresh_observed = _observe(session, state)
                    fresh_progress = _progress(session, state, fresh_observed)
                    if fresh_progress['next_state'] != step or fresh_observed['fingerprints'] != observed['fingerprints']:
                        output_fn('Evidence changed; review invalidated prerequisites.'); continue
                    observed = fresh_observed
                    if state['mode'] == 'live' and STAGES.index(step) >= STAGES.index('plan'):
                        output_fn('Live blocked: ' + ', '.join(LIVE_BLOCKERS)); continue
                    if step == 'generation': _generate(session, state, observed, guard)
                    else:
                        if step == 'atmos' and state.get('atmos_executable') is not None:
                            from .journey_native_atmos import execute
                            execute(state['repository'], observed['context']['stack'], observed['context']['component'],
                                    state['atmos_executable'], _root(session) / 'native-atmos.json')
                        if step == 'plan': _prepare_plan(session, state, observed)
                        if step == 'approval':
                            from .protected import approve_synthetic_operation, approve_native_local_operation
                            approve = approve_native_local_operation if state.get('tofu_executable') else approve_synthetic_operation
                            approval = approve(_request(session, state, observed), executor=_native(session))
                        if step == 'execute':
                            if approval is None:
                                _invalidate(session, 'approval'); output_fn('Fresh in-process local-operation approval is required.'); continue
                            from .protected import execute_native_operation
                            state['in_flight'] = 'execute'; write_json(session, state)
                            result = execute_native_operation(_request(session, state, observed), _root(session) / 'operations', executor=_native(session), approval=approval)
                            approval = None; write_json(_root(session) / 'native-result.json', result)
                            if result.get('status') == 'rejected':
                                # The protected dispatcher uses rejected only
                                # before dispatch; uncertain dispatch is distinct.
                                state['in_flight'] = None
                                _invalidate(session, 'approval')
                                raise AppError('journey_execution_rejected', 'Local preflight rejected execution; review or replan before a fresh approval.')
                            if result.get('status') != 'succeeded_verified':
                                raise AppError('journey_execution_unknown', 'Local execution needs independent reconciliation; no replay.')
                            _readback_service(session, state, observed)
                        if step == 'convergence' and state.get('tofu_executable') is not None:
                            from .protected import verify_native_convergence
                            report = verify_native_convergence(_native(session), _request(session, state, observed))
                            write_json(_root(session) / 'native-convergence.json', report)
                        _checkpoint(session, state, observed, step, guard)
                        if step == 'execute': state['in_flight'] = None
                        if step == 'handoff': return finish('complete_simulation')
                else: output_fn('Use the command for the displayed stage.')
            except (AppError, OSError, ValueError, ImportError) as error:
                output_fn('Local action stopped: ' + getattr(error, 'code', 'local_operation_failed'))
            guard(); write_json(session, state)
    except (EOFError, KeyboardInterrupt): return finish('suspended')


def run_journey(session_path, input_path=None, context_path=None, output_path=None,
                input_fn=input, output_fn=print, repo=None, stack=None, component=None, mode=None, atmos_executable=None, tofu_executable=None):
    """Run all local stages. ``mode='live'`` reviews proposals then reports gates.

    Cloud mutation and native provider execution are never available here.
    Explicit pinned Atmos can compare admitted repository configuration only.
    Existing single-policy and guided sessions use different schemas.
    """
    lock = None; identity = None; result = None; token = (secrets.token_hex(32) + '\n').encode()
    try:
        session = _safe(session_path)
        def requested():
            fresh = not session.exists()
            if fresh:
                if any(value is None for value in (input_path, context_path, output_path)):
                    raise AppError('journey_paths_required', 'First use needs input, context and output paths.')
                state = {'schema_version': VERSION, 'paths': {key: str(_safe(value)) for key, value in
                         (('input', input_path), ('context', context_path), ('output', output_path))},
                         'repository': str(_safe(repo)) if repo else None, 'target': {}, 'selected_ids': [],
                         'mode': mode or 'simulation', 'lifecycle': 'active', 'in_flight': None, 'completed': []}
            else:
                state = _load(session)
                if mode is not None and mode != state['mode']:
                    raise AppError('journey_mode_change', 'Use a fresh session when changing simulation/live review mode.')
                for key, value in (('input', input_path), ('context', context_path), ('output', output_path)):
                    if value is not None:
                        candidate = str(_safe(value))
                        if state['in_flight'] is not None and candidate != state['paths'][key]:
                            raise AppError('journey_pending_operation_binding', 'Reconcile the pending operation with its original evidence before editing paths.')
                        state['paths'][key] = candidate
                if repo is not None:
                    candidate = str(_safe(repo))
                    if state['in_flight'] is not None and candidate != state['repository']:
                        raise AppError('journey_pending_operation_binding', 'Reconcile the pending operation with its original repository.')
                    state['repository'] = candidate
            if atmos_executable is not None:
                candidate = str(_safe(atmos_executable))
                if state['repository'] is None:
                    raise AppError('journey_atmos_repository_required', 'Use --repo with --atmos-executable so effective configuration is source-bound.')
                if state['in_flight'] is not None and candidate != state.get('atmos_executable'):
                    raise AppError('journey_pending_operation_binding', 'Reconcile the pending operation before changing the Atmos executable.')
                state['atmos_executable'] = candidate
            if tofu_executable is not None:
                candidate = str(_safe(tofu_executable))
                if state['in_flight'] is not None and candidate != state.get('tofu_executable'):
                    raise AppError('journey_pending_operation_binding', 'Reconcile the pending operation before changing the OpenTofu executable.')
                state['tofu_executable'] = candidate
            for key, value in (('stack', stack), ('component', component)):
                if value is not None:
                    if not isinstance(value, str) or not re.fullmatch(r'[A-Za-z0-9_./-]{1,256}', value):
                        raise AppError('journey_invalid_target', 'Target selectors must be bounded literals.')
                    if state['in_flight'] is not None and value != state['target'].get(key):
                        raise AppError('journey_pending_operation_binding', 'Reconcile the pending operation with its original target.')
                    state['target'][key] = value
            if state['mode'] not in ('simulation', 'live'): raise AppError('journey_invalid_mode', 'Select simulation or live review.')
            _validate_paths(session, state)
            return state, fresh
        requested()
        lock = session.parent / ('.intune-wizard-lock-' + hashlib.sha256(str(session).encode()).hexdigest()[:32])
        mkdir_durable(lock.parent)
        try: fd = os.open(lock, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        except FileExistsError: raise AppError('wizard_session_locked', 'Inspect the existing session lock before resuming.') from None
        with os.fdopen(fd, 'wb') as stream:
            info = os.fstat(stream.fileno()); identity = (info.st_dev, info.st_ino)
            stream.write(token); stream.flush(); os.fsync(stream.fileno())
        sync_directory(lock.parent)
        def guard():
            if not workflow._owns_lock(lock, identity, token): raise AppError('wizard_lock_lost', 'Session lock ownership changed.')
        state, fresh = requested(); guard()
        output_fn('Full local Intune journey: production proposals retain gates; ' +
                  ('execution uses pinned OpenTofu on a disposable output-only local fixture with modeled Intune semantics.'
                   if state.get('tofu_executable') else 'execution is a bounded synthetic child process only.'))
        result = _run(session, state, fresh, input_fn, output_fn, guard)
        return result
    except (AppError, OSError, ValueError) as error:
        result = {'status': 'blocked', 'error': getattr(error, 'code', 'local_operation_failed'),
                  'session': str(session_path), 'execution_authorized': False, 'live_ready': False, 'live_blockers': list(LIVE_BLOCKERS)}
        return result
    finally:
        if identity is not None:
            try:
                if not workflow._owns_lock(lock, identity, token):
                    raise OSError('session lock ownership was lost before cleanup')
                lock.unlink(missing_ok=True)
                sync_directory(lock.parent)
            except OSError:
                # A cleanup failure must not turn an unproven durable unlock
                # into a successful completion or escape as a raw traceback.
                return {'status': 'blocked', 'error': 'journey_lock_cleanup_unconfirmed',
                        'session': str(session_path), 'execution_authorized': False,
                        'live_ready': False, 'live_blockers': list(LIVE_BLOCKERS),
                        'pre_cleanup_result': result}
