"""Fixed, bounded native process execution for disposable LOCAL fixtures only.

This is not an Intune adapter. An output-only OpenTofu configuration and a
separate explicitly synthetic subprocess exercise the real saved-plan boundary.
No request, attestation, or approval JSON can enable cloud execution.
"""
from __future__ import annotations

import hashlib
import ctypes
import os
from pathlib import Path
import re
import selectors
import signal
import stat
import subprocess
import sys
import time
import uuid

from .execution import review_plan, review_local_output_plan
from .io import AppError, canonical, digest, load_json, parse_json, read_bytes

VERSION = 'protected-local/1.0'
from .native_pins import OPENTOFU_CURRENT_SHA256, OPENTOFU_PINS
NATIVE_SHA256 = OPENTOFU_CURRENT_SHA256
MAX_OUTPUT = 2 * 1024 * 1024
PROCESS_TIMEOUT = 30
PROCESS_CLEANUP_TIMEOUT = 2.0
PROCESS_CLEANUP_POLL = 0.005
MAX_PROC_ENTRIES = 65536
MAX_GROUP_TASKS = 65536
CHILD_ADDRESS_SPACE_BYTES = 4 * 1024**3
CHILD_CPU_SECONDS = 20
CHILD_FILE_BYTES = 64 * 1024**2
CHILD_FILE_DESCRIPTORS = 256
_ID = re.compile(r'^[0-9a-f]{32}$')
_SECRET = object()
_EVENT_KINDS = ('prepared', 'authorized', 'dispatch_started', 'readback_verified', 'completed')
_REQUEST_KEYS = {'schema_version','mode','action','operation_id','created_at','expires_at','bindings','binding_sha256','review','execution_authorized'}
_BINDING_KEYS = {'root_sha256','executable_sha256','worker_sha256','implementation_sha256','configuration_sha256','saved_plan_sha256','plan_json_sha256','before_state_sha256','before_value_sha256','before_lineage_sha256','before_serial','desired_value_sha256'}

# The fixture accepts exactly the same fixed operations as the native runner.
# This source is generated by the package, never by request JSON.
_WORKER = r'''import hashlib,json,os,sys,tempfile
from pathlib import Path
root=Path.cwd()
def canonical(v):return json.dumps(v,sort_keys=True,separators=(',',':'),ensure_ascii=False,allow_nan=False).encode()
def load(p):return json.loads(p.read_bytes())
def save(p,v):
 data=canonical(v); fd,name=tempfile.mkstemp(dir=p.parent)
 with os.fdopen(fd,'wb') as f:f.write(data);f.flush();os.fsync(f.fileno())
 os.replace(name,p)
 fd=os.open(p.parent,os.O_RDONLY);os.fsync(fd);os.close(fd)
state=root/'state/terraform.tfstate';plan=Path(sys.argv[2]) if len(sys.argv)>2 else root/'saved.tfplan';cmd=sys.argv[1]
if cmd=='version':print('{"terraform_version":"synthetic-local-1"}')
elif cmd=='init':pass
elif cmd=='plan':
 s=load(state);v=load(root/'main.tf.json')['output']['fixture']['value']
 save(plan,{'schema':'synthetic-saved-plan/1','before_sha256':hashlib.sha256(state.read_bytes()).hexdigest(),'value':v})
elif cmd=='show':
 p=load(plan);s=load(state);before=s['outputs']['fixture']['value'];after=p['value'];change=canonical(before)!=canonical(after)
 print(json.dumps({'format_version':'1.2','terraform_version':'1.10.0','planned_values':{'outputs':{'fixture':{'value':after,'sensitive':False}}},'resource_changes':[],'configuration':{},'output_changes':{'fixture':{'actions':['update' if change else 'no-op'],'before':before,'after':after,'after_unknown':False,'before_sensitive':False,'after_sensitive':False}},'prior_state':{'format_version':'1.0','terraform_version':'1.10.0','values':{'outputs':{'fixture':{'value':before,'sensitive':False,'type':['object',{}]}}}}}))
elif cmd=='apply':
 p=load(plan)
 if p['before_sha256']!=hashlib.sha256(state.read_bytes()).hexdigest():sys.exit(3)
 s=load(state);s['serial']+=1;s['outputs']['fixture']['value']=p['value'];save(state,s)
else:sys.exit(2)
'''.encode()


def _now(): return int(time.time())


def _fail(code): raise AppError(code, 'Protected local operation could not be verified.')


def _path(value):
    if not isinstance(value, (str, os.PathLike)) or not str(value) or '\x00' in str(value): _fail('invalid_path')
    path = Path(value).absolute()
    if any(p.is_symlink() for p in (path, *path.parents)): _fail('unsafe_path')
    return path.resolve()


def _json_snapshot(value):
    # Bound Python inputs before serialization, including cyclic containers.
    pending=[(value,0)]; nodes=0
    while pending:
        item, depth=pending.pop(); nodes+=1
        if depth>32 or nodes>10000: _fail('invalid_document')
        if type(item) is dict:
            if len(item)>2048 or any(type(k)is not str or len(k)>512 for k in item): _fail('invalid_document')
            pending.extend((v,depth+1) for v in item.values())
        elif type(item) is list: pending.extend((v,depth+1) for v in item)
        elif item is not None and type(item) not in (str,int,bool,float): _fail('invalid_document')
        if type(item)is str and ('${' in item or '%{' in item): _fail('configuration_interpolation_unsupported')
    data=canonical(value)
    if len(data)>1024*1024: _fail('invalid_document')
    return parse_json(data)


def _sync(path):
    fd=os.open(path,os.O_RDONLY | getattr(os,'O_DIRECTORY',0))
    try: os.fsync(fd)
    finally: os.close(fd)


def _exclusive(path, data, mode=0o600):
    path=_path(path)
    fd=os.open(path,os.O_WRONLY|os.O_CREAT|os.O_EXCL|getattr(os,'O_NOFOLLOW',0),mode)
    with os.fdopen(fd,'wb') as out: out.write(data); out.flush(); os.fsync(out.fileno())
    _sync(path.parent)


def _sha(path, *, max_bytes=256*1024*1024):
    path=_path(path); h=hashlib.sha256(); total=0
    fd=os.open(path,os.O_RDONLY|getattr(os,'O_NOFOLLOW',0)|getattr(os,'O_NONBLOCK',0))
    with os.fdopen(fd,'rb') as stream:
        if not stat.S_ISREG(os.fstat(stream.fileno()).st_mode): _fail('invalid_file')
        while True:
            chunk=stream.read(1024*1024)
            if not chunk: break
            total+=len(chunk)
            if total>max_bytes: _fail('input_too_large')
            h.update(chunk)
    return h.hexdigest()


def _native_profile(executable, executable_sha):
    profile = OPENTOFU_PINS.get(executable_sha)
    if profile is None or Path(executable).stat().st_size != profile['bytes']:
        _fail('unqualified_executable')
    return profile


def _engine_version(executor):
    return (_native_profile(executor.executable, executor.manifest['executable_sha256'])['version']
            if executor.mode == 'native_local_opentofu_only' else '1.10.0')


def _configuration(value, version='1.10.0'):
    return {'terraform':{'required_version':'= ' + version,'backend':{'local':{'path':'state/terraform.tfstate'}}},'output':{'fixture':{'value':value}}}


class SyntheticExecutor:
    """Concrete local process fixture; only create_synthetic_executor creates it."""
    mode='synthetic_local_process_only'
    def __init__(self, root):
        self.root=_path(root)
        self.manifest=load_json(self.root/'executor.json')
        if self.manifest.get('mode')!=self.mode: _fail('wrong_executor_mode')
        if set(self.manifest)!={'schema_version','mode','executable','executable_sha256','desired_value_sha256'} or self.manifest['schema_version']!=VERSION: _fail('invalid_executor')
        self.executable=_path(self.manifest['executable'])
        self._validate()

    def _validate(self):
        if self.executable != self.root/'tool': _fail('invalid_executable')
        if _sha(self.executable)!=self.manifest['executable_sha256']: _fail('executable_changed')
        if self.mode=='native_local_opentofu_only': _native_profile(self.executable,self.manifest['executable_sha256'])
        if self.mode=='synthetic_local_process_only' and self.manifest['executable_sha256']!=_sha(Path(sys.executable).resolve()): _fail('unqualified_executable')
        if self.mode=='synthetic_local_process_only' and read_bytes(self.root/'pyvenv.cfg')!=('home = '+str(Path(sys.executable).resolve().parent)+'\ninclude-system-site-packages = false\n').encode(): _fail('runtime_changed')
        if self.mode=='synthetic_local_process_only' and _sha(self.root/'worker.py')!=hashlib.sha256(_WORKER).hexdigest(): _fail('worker_changed')
        config=_json_snapshot(load_json(self.root/'work/main.tf.json'))
        if set(config)!={'terraform','output'} or set(config.get('output',{}))!={'fixture'} or set(config['output']['fixture'])!={'value'}: _fail('unsupported_configuration')
        if config!=_configuration(config['output']['fixture']['value'], _engine_version(self)): _fail('unsupported_configuration')
        if digest(config['output']['fixture']['value'])!=self.manifest['desired_value_sha256']: _fail('configuration_changed')
        if read_bytes(self.root/'tofu.rc')!=b'disable_checkpoint = true\n': _fail('cli_configuration_changed')
        allowed={'main.tf.json','state','saved.tfplan','.terraform','plan.json','second.tfplan','second-plan.json'}
        for index,path in enumerate((self.root/'work').iterdir()):
            if index>=len(allowed) or path.name not in allowed or path.is_symlink(): _fail('unexpected_runtime_files')
            if path.name in ('state','.terraform'):
                nested={'terraform.tfstate','terraform.tfstate.backup','.terraform.tfstate.lock.info'} if path.name=='state' else {'terraform.tfstate'}
                for count,item in enumerate(path.iterdir()):
                    if count>=len(nested) or item.name not in nested or item.is_symlink() or not item.is_file(): _fail('unexpected_runtime_files')
            elif not path.is_file(): _fail('unexpected_runtime_files')
        # Native initialization must retain exactly the generated local backend.
        metadata=self.root/'work/.terraform/terraform.tfstate'
        if self.mode=='native_local_opentofu_only' and metadata.exists():
            backend=load_json(metadata).get('backend',{})
            if backend.get('type')!='local' or backend.get('config',{}).get('path')!='state/terraform.tfstate': _fail('backend_changed')


class NativeLocalExecutor(SyntheticExecutor):
    """Exact pinned OpenTofu, generated output-only configuration, local state."""
    mode='native_local_opentofu_only'


def _create(root, initial_value, desired_value, executable, mode):
    if sys.platform!='linux': _fail('unsupported_platform')
    initial_value,desired_value=_json_snapshot(initial_value),_json_snapshot(desired_value)
    executable=_path(executable); executable_sha=_sha(executable)
    version = _native_profile(executable,executable_sha)['version'] if mode=='native_local_opentofu_only' else '1.10.0'
    root=_path(root); root.mkdir(mode=0o700)
    (root/'work').mkdir(mode=0o700); (root/'work/state').mkdir(mode=0o700); (root/'home').mkdir(mode=0o700)
    # Copy the qualified executable into the private target to pin subsequent opens.
    with executable.open('rb') as source:
        fd=os.open(root/'tool',os.O_WRONLY|os.O_CREAT|os.O_EXCL,0o500)
        with os.fdopen(fd,'wb') as out:
            while True:
                chunk=source.read(1024*1024)
                if not chunk:break
                out.write(chunk)
            out.flush();os.fsync(out.fileno())
    if _sha(root/'tool')!=executable_sha: _fail('executable_changed')
    _exclusive(root/'tofu.rc',b'disable_checkpoint = true\n')
    _exclusive(root/'worker.py',_WORKER,0o400)
    if mode=='synthetic_local_process_only':
        _exclusive(root/'pyvenv.cfg',('home = '+str(Path(sys.executable).resolve().parent)+'\ninclude-system-site-packages = false\n').encode(),0o400)
    manifest={'schema_version':VERSION,'mode':mode,'executable':str(root/'tool'),'executable_sha256':executable_sha,'desired_value_sha256':digest(desired_value)}
    if mode=='synthetic_local_process_only':
        _exclusive(root/'work/state/terraform.tfstate',canonical({'version':4,'lineage':str(uuid.uuid4()),'serial':0,'outputs':{'fixture':{'value':initial_value}}}))
    else:
        # Bootstrap is explicitly confined to the new disposable local fixture.
        _exclusive(root/'work/main.tf.json',canonical(_configuration(initial_value, version)))
        bootstrap=dict(manifest,desired_value_sha256=digest(initial_value))
        _exclusive(root/'executor.json',canonical(bootstrap))
        executor=NativeLocalExecutor(root)
        observed_version=parse_json(_run(executor,'version'))
        if observed_version.get('terraform_version')!=version: _fail('unqualified_engine_version')
        _run(executor,'init'); _run(executor,'plan'); _run(executor,'apply')
        (root/'executor.json').unlink(); (root/'work/main.tf.json').unlink(); (root/'work/saved.tfplan').unlink()
    _exclusive(root/'executor.json',canonical(manifest))
    _exclusive(root/'work/main.tf.json',canonical(_configuration(desired_value, version)))
    _sync(root)
    return SyntheticExecutor(root) if mode=='synthetic_local_process_only' else NativeLocalExecutor(root)


def create_synthetic_executor(root, *, initial_value, desired_value):
    return _create(root,initial_value,desired_value,Path(sys.executable).resolve(),'synthetic_local_process_only')


def create_native_local_executor(root, *, executable, initial_value, desired_value):
    """Create disposable local fixture using the package's exact Linux AMD64 pin."""
    return _create(root,initial_value,desired_value,executable,'native_local_opentofu_only')


def _environment(executor):
    return {'HOME':str(executor.root/'home'),'PATH':'/usr/bin:/bin','LANG':'C','LC_ALL':'C',
            'TF_IN_AUTOMATION':'1','TF_INPUT':'0','TF_WORKSPACE':'default',
            'TF_CLI_CONFIG_FILE':str(executor.root/'tofu.rc'), 'CHECKPOINT_DISABLE':'1'}


def _command(executor, command, executable, worker=None, saved_plan=None):
    second=command in ('second_plan','second_show')
    if second and type(executor)is not NativeLocalExecutor:_fail('wrong_executor_mode')
    plan=saved_plan or str(executor.root/'work'/('second.tfplan' if second else 'saved.tfplan'))
    commands={'version':['version','-json'], 'init':['init','-input=false','-no-color'],
              'plan':['plan','-input=false','-no-color','-lock=true','-lock-timeout=0s','-refresh=true','-out='+plan],
              'show':['show','-json',plan],
              'second_plan':['plan','-input=false','-no-color','-lock=true','-lock-timeout=0s','-refresh=true','-out='+plan],
              'second_show':['show','-json',plan],
              'apply':['apply','-input=false','-no-color','-lock=true','-lock-timeout=0s',plan]}
    if command not in commands: _fail('unknown_command')
    return [executable,'-I','-S',worker,command]+([plan] if saved_plan else []) if executor.mode=='synthetic_local_process_only' else [executable,*commands[command]]


def _network_filter():
    """Prepare a fail-closed Linux filter before fork; callback only loads it."""
    if sys.platform!='linux' or os.uname().machine!='x86_64':_fail('unsupported_platform')
    import resource
    limits=((resource.RLIMIT_AS,CHILD_ADDRESS_SPACE_BYTES),(resource.RLIMIT_CPU,CHILD_CPU_SECONDS),
            (resource.RLIMIT_FSIZE,CHILD_FILE_BYTES),(resource.RLIMIT_NOFILE,CHILD_FILE_DESCRIPTORS),
            (resource.RLIMIT_CORE,0))
    # Never raise an inherited host limit while imposing our deterministic ceiling.
    limits=tuple((kind,min(value,hard) if hard!=resource.RLIM_INFINITY else value)
                 for kind,value in limits for _,hard in (resource.getrlimit(kind),))
    lib=ctypes.CDLL('libseccomp.so.2',use_errno=True)
    lib.seccomp_init.argtypes=[ctypes.c_uint32];lib.seccomp_init.restype=ctypes.c_void_p
    lib.seccomp_syscall_resolve_name.argtypes=[ctypes.c_char_p];lib.seccomp_syscall_resolve_name.restype=ctypes.c_int
    lib.seccomp_rule_add.argtypes=[ctypes.c_void_p,ctypes.c_uint32,ctypes.c_int,ctypes.c_uint];lib.seccomp_rule_add.restype=ctypes.c_int
    lib.seccomp_load.argtypes=[ctypes.c_void_p];lib.seccomp_load.restype=ctypes.c_int
    lib.seccomp_release.argtypes=[ctypes.c_void_p]
    class ArgumentComparison(ctypes.Structure):
        _fields_=[('arg',ctypes.c_uint),('op',ctypes.c_int),('datum_a',ctypes.c_uint64),('datum_b',ctypes.c_uint64)]
    lib.seccomp_rule_add_array.argtypes=[ctypes.c_void_p,ctypes.c_uint32,ctypes.c_int,ctypes.c_uint,ctypes.POINTER(ArgumentComparison)]
    lib.seccomp_rule_add_array.restype=ctypes.c_int
    context=lib.seccomp_init(0x7fff0000)
    if not context:_fail('network_guard_unavailable')
    try:
        for name in ('socket','socketpair','connect','bind','listen','accept','accept4','sendto','sendmsg','sendmmsg','recvfrom','recvmsg','recvmmsg','fork','vfork'):
            number=lib.seccomp_syscall_resolve_name(name.encode())
            if number<0 or lib.seccomp_rule_add(context,0x00050001,number,0)!=0:_fail('network_guard_unavailable')
        # Permit Go/Python runtime threads, never a new process. CLONE_THREAD
        # requires shared VM/signal handlers on Linux. clone3's pointer flags
        # cannot be inspected by seccomp; ENOSYS permits libc's clone fallback.
        number=lib.seccomp_syscall_resolve_name(b'clone')
        comparison=ArgumentComparison(0,7,0x00010000,0)
        if number<0 or lib.seccomp_rule_add_array(context,0x00050001,number,1,ctypes.byref(comparison))!=0:_fail('network_guard_unavailable')
        number=lib.seccomp_syscall_resolve_name(b'clone3')
        if number<0 or lib.seccomp_rule_add(context,0x00050026,number,0)!=0:_fail('network_guard_unavailable')
    except BaseException:
        lib.seccomp_release(context);raise
    def child():
        try:
            for kind,value in limits:resource.setrlimit(kind,(value,value))
        except (OSError,ValueError):os._exit(125)
        if lib.seccomp_load(context)!=0:os._exit(125)
        os.umask(0o077)
    return child,lambda:lib.seccomp_release(context)


def _read_process_stat(path):
    """Read bounded Linux procfs identity; comm may contain ')' or newlines."""
    with Path(path).open('rb') as stream:
        raw = stream.read(8193)
    if len(raw) > 8192:
        _fail('process_cleanup_observation_invalid')
    try:
        prefix, separator, tail = raw.rpartition(b') ')
        pid, opening, _ = prefix.partition(b' (')
        fields = tail.split()
        if not separator or not opening or len(fields) < 20 or fields[0] not in tuple(bytes([c]) for c in b'RSDZTWtXxKWPIN'):
            raise ValueError()
        value = {'pid': int(pid), 'state': fields[0].decode('ascii'),
                 'pgrp': int(fields[2]), 'session': int(fields[3]), 'starttime': int(fields[19])}
        if value['pid'] <= 0 or min(value['pgrp'], value['session'], value['starttime']) < 0:
            raise ValueError()
        return value
    except (ValueError, IndexError, UnicodeError):
        _fail('process_cleanup_observation_invalid')


def _process_group_members(pgid, *, deadline):
    """Census the original group, including threads of zombie group leaders.

    This requires readable Linux procfs in the caller's PID namespace. Missing
    entries are ordinary exits; denied/malformed/incomplete observations are
    failures. It is not a detector for processes that escaped this group.
    """
    members = []; entries = 0; tasks = 0
    with os.scandir('/proc') as processes:
        for entry in processes:
            entries += 1
            if entries > MAX_PROC_ENTRIES:
                _fail('process_cleanup_observation_limit')
            if time.monotonic() >= deadline:
                _fail('process_cleanup_timeout')
            if not entry.name.isascii() or not entry.name.isdigit():
                continue
            try:
                leader = _read_process_stat(Path(entry.path) / 'stat')
            except (FileNotFoundError, ProcessLookupError):
                continue
            if leader['pid'] != int(entry.name):
                _fail('process_cleanup_observation_invalid')
            if leader['pgrp'] != pgid:
                continue
            if leader['session'] != pgid:
                _fail('process_cleanup_group_changed')
            try:
                with os.scandir(Path(entry.path) / 'task') as threads:
                    for thread in threads:
                        tasks += 1
                        if tasks > MAX_GROUP_TASKS:
                            _fail('process_cleanup_observation_limit')
                        if time.monotonic() >= deadline:
                            _fail('process_cleanup_timeout')
                        if not thread.name.isascii() or not thread.name.isdigit():
                            _fail('process_cleanup_observation_invalid')
                        try:
                            observed = _read_process_stat(Path(thread.path) / 'stat')
                        except (FileNotFoundError, ProcessLookupError):
                            continue
                        if observed['pid'] != int(thread.name) or observed['pgrp'] != pgid or observed['session'] != pgid:
                            _fail('process_cleanup_group_changed')
                        members.append({'pid': leader['pid'], 'tid': observed['pid'],
                                        'state': observed['state'], 'starttime': observed['starttime']})
            except (FileNotFoundError, ProcessLookupError):
                continue
    return members


def _peek_process_exit(process):
    """Observe, but do not reap, the owned child that reserves the group ID."""
    observed = os.waitid(os.P_PID, process.pid, os.WEXITED | os.WNOHANG | os.WNOWAIT)
    if observed is None:
        return None
    if observed.si_pid != process.pid or observed.si_code not in (os.CLD_EXITED, os.CLD_KILLED, os.CLD_DUMPED):
        _fail('process_cleanup_anchor_lost')
    return observed.si_status if observed.si_code == os.CLD_EXITED else -observed.si_status


def _wait_process_exit(process, *, deadline, active_check=None, timeout_code='process_timeout'):
    while True:
        if active_check is not None:
            active_check()
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            _fail(timeout_code)
        result = _peek_process_exit(process)
        if result is not None:
            return result
        time.sleep(min(0.01, remaining))


def _cleanup_process_group(process, *, evidence):
    """Kill and confirm bounded cleanup before releasing the original PID.

    The unreaped direct child anchors its PID/PGID against reuse. Two complete
    procfs censuses must contain no live group thread. This is cooperative
    process-group cleanup, not host containment: protected execution denies
    new processes; the provider guard permits them but denies group escape.
    """
    deadline = time.monotonic() + PROCESS_CLEANUP_TIMEOUT
    evidence.update(status='unverified', group_id=process.pid,
                    scope='original_linux_process_group_only', observations=0,
                    deadline_seconds=PROCESS_CLEANUP_TIMEOUT, direct_child_reaped=False)
    cleanup_error = None; owned_child = False; group_signalled = False
    try:
        # waitid also proves this is still our child before any group signal.
        _peek_process_exit(process)
        owned_child = True
        if os.getpgid(process.pid) != process.pid or os.getsid(process.pid) != process.pid:
            _fail('process_cleanup_anchor_lost')
        # Procfs observation may itself fail. First stop the already-confirmed
        # owned group, so an unreadable stat cannot leave a known child live.
        os.killpg(process.pid, signal.SIGKILL)
        group_signalled = True
        anchor = _read_process_stat(Path('/proc') / str(process.pid) / 'stat')
        if anchor['pid'] != process.pid or anchor['pgrp'] != process.pid or anchor['session'] != process.pid:
            _fail('process_cleanup_anchor_lost')
        evidence['leader_starttime'] = anchor['starttime']
        quiet = 0; previous_terminal = None
        while True:
            if time.monotonic() >= deadline:
                _fail('process_cleanup_timeout')
            # Repeated signals include children created just before the first
            # signal; no group signal is issued after the leader is reaped.
            os.killpg(process.pid, signal.SIGKILL)
            members = _process_group_members(process.pid, deadline=deadline)
            evidence['observations'] += 1
            live = [item for item in members if item['state'] not in ('Z', 'X', 'x')]
            evidence['live_members'] = live
            terminal = frozenset((item['pid'], item['tid'], item['starttime']) for item in members)
            quiet = quiet + 1 if not live and terminal == previous_terminal else 1 if not live else 0
            previous_terminal = terminal if not live else None
            if quiet >= 2 and _peek_process_exit(process) is not None:
                break
            time.sleep(min(PROCESS_CLEANUP_POLL, max(0, deadline - time.monotonic())))
    except BaseException as error:
        cleanup_error = error
        evidence['observation_error'] = getattr(error, 'code', type(error).__name__)
        if owned_child and not group_signalled:
            # Group identity was not established. Signal only our unreaped
            # direct child, never an unverified or possibly reused group.
            try: os.kill(process.pid, signal.SIGKILL)
            except ProcessLookupError: pass
            except BaseException as signal_error:
                evidence['signal_error'] = getattr(signal_error, 'code', type(signal_error).__name__)
    finally:
        # Bounded direct-child reaping also runs on incomplete observation.
        # It is never used as evidence that an orphan descendant exited.
        try:
            process.wait(timeout=max(0, deadline - time.monotonic()))
            evidence['direct_child_reaped'] = owned_child
        except BaseException as error:
            if cleanup_error is None:
                cleanup_error = error
            evidence['reap_error'] = getattr(error, 'code', type(error).__name__)
    if cleanup_error is not None:
        code = 'process_cleanup_timeout' if (getattr(cleanup_error, 'code', None) == 'process_cleanup_timeout'
                                             or isinstance(cleanup_error, subprocess.TimeoutExpired)) else 'process_cleanup_unverified'
        _fail(code)
    evidence['status'] = 'confirmed'


def _release_process_resources(process, selector, release):
    """Attempt every local release even when an earlier release fails."""
    callbacks = [release, selector.close]
    if process is not None:
        callbacks.extend(pipe.close for pipe in (process.stdout, process.stderr) if pipe is not None)
    errors = []
    for callback in callbacks:
        try: callback()
        except BaseException as error:
            errors.append(getattr(error, 'code', type(error).__name__))
    return errors


def _supervise(argv, *, cwd, env, pass_fds=(), timeout=PROCESS_TIMEOUT, output_limit=MAX_OUTPUT, executable=None, evidence=None):
    """Private primitive: byte-bounded pipes and process-group deadline on Linux."""
    if type(timeout) is not int or not 1<=timeout<=60 or type(output_limit)is not int or not 1<=output_limit<=MAX_OUTPUT: _fail('invalid_process_bound')
    if evidence is not None and type(evidence)is not dict:_fail('invalid_process_evidence')
    process=None; selector=selectors.DefaultSelector(); output=bytearray(); errors=bytearray(); total=0
    release_guard=lambda:None
    try:
        guard,release_guard=_network_filter()
        process=subprocess.Popen(argv,cwd=cwd,env=env,stdin=subprocess.DEVNULL,stdout=subprocess.PIPE,stderr=subprocess.PIPE,
                                 shell=False,close_fds=True,pass_fds=pass_fds,start_new_session=True,executable=executable,preexec_fn=guard)
        for pipe in (process.stdout,process.stderr):
            os.set_blocking(pipe.fileno(),False);selector.register(pipe,selectors.EVENT_READ)
        deadline=time.monotonic()+timeout
        while selector.get_map():
            remaining=deadline-time.monotonic()
            if remaining<=0: _fail('process_timeout')
            for key,_ in selector.select(min(remaining,0.1)):
                chunk=os.read(key.fileobj.fileno(),65536)
                if not chunk: selector.unregister(key.fileobj);continue
                total+=len(chunk)
                if total>output_limit: _fail('process_output_limit')
                if key.fileobj is process.stdout:output.extend(chunk)
                else:errors.extend(chunk)
        return_code=_wait_process_exit(process,deadline=deadline)
        if return_code!=0: _fail('process_failed')
        return bytes(output)
    finally:
        primary=sys.exc_info()[1];cleanup={};cleanup_error=None
        try:
            if process is not None:_cleanup_process_group(process,evidence=cleanup)
        except BaseException as error:
            cleanup_error=error
        finally:
            resource_errors=_release_process_resources(process,selector,release_guard)
            if evidence is not None:
                evidence.update(stdout_bytes=bytes(output),stderr_bytes=bytes(errors),
                                exit_code=process.returncode if process is not None else None,
                                output_truncated=total>output_limit,process_cleanup=cleanup,
                                resource_errors=resource_errors,
                                primary_error=getattr(primary,'code',type(primary).__name__) if primary else None)
        if cleanup_error is not None:raise cleanup_error from primary
        if resource_errors and primary is None:_fail('process_cleanup_resources')


def _run(executor, command):
    _require_executor(executor); executor._validate(); descriptors=[]
    if command=='second_plan' and (executor.root/'work/second.tfplan').exists():_fail('second_plan_exists')
    try:
        pinned=[(executor.executable,executor.manifest['executable_sha256'])]
        if executor.mode=='synthetic_local_process_only':pinned.append((executor.root/'worker.py',hashlib.sha256(_WORKER).hexdigest()))
        if command in ('show','apply','second_show'):
            plan_path=executor.root/'work'/('second.tfplan' if command=='second_show' else 'saved.tfplan')
            expected=_sha(plan_path)
            preparation=executor.root/'preparation.json'
            if command!='second_show' and preparation.exists():expected=load_json(preparation)['bindings']['saved_plan_sha256']
            pinned.append((plan_path,expected))
        for path,expected in pinned:
            fd=os.open(_path(path),os.O_RDONLY|getattr(os,'O_NOFOLLOW',0));descriptors.append(fd)
            with os.fdopen(os.dup(fd),'rb') as source:
                if hashlib.file_digest(source,'sha256').hexdigest()!=expected:_fail('evidence_changed')
        saved_plan='/proc/self/fd/'+str(descriptors[-1]) if command in ('show','apply','second_show') else None
        arguments=_command(executor,command,str(executor.executable),
                           '/proc/self/fd/'+str(descriptors[1]) if executor.mode=='synthetic_local_process_only' else None,saved_plan)
        return _supervise(arguments,cwd=executor.root/'work',env=_environment(executor),pass_fds=tuple(descriptors),executable='/proc/self/fd/'+str(descriptors[0]))
    finally:
        for fd in descriptors:os.close(fd)


def _require_executor(executor):
    if type(executor) not in (SyntheticExecutor,NativeLocalExecutor): _fail('unsupported_executor')


def _state(executor):
    path=executor.root/'work/state/terraform.tfstate'; document=load_json(_path(path))
    if document.get('resources',[])!=[]: _fail('unsupported_state_resources')
    if type(document.get('serial'))is not int or document['serial']<0 or not isinstance(document.get('lineage'),str): _fail('invalid_state')
    outputs=document.get('outputs')
    if not isinstance(outputs,dict) or set(outputs)!={'fixture'} or 'value' not in outputs['fixture']: _fail('invalid_state')
    return {'state_sha256':_sha(path),'value_sha256':digest(outputs['fixture']['value']),'serial':document['serial'],'lineage_sha256':digest(document['lineage'])}


def inspect_executor(executor):
    _require_executor(executor);executor._validate();state=_state(executor)
    return dict(state,mode=executor.mode,desired_value_sha256=executor.manifest['desired_value_sha256'],execution_authorized=False)


def _bindings(executor):
    state=_state(executor)
    return {'root_sha256':digest(str(executor.root)),'executable_sha256':_sha(executor.executable),
            'worker_sha256':_sha(executor.root/'worker.py'),'implementation_sha256':digest([_sha(__file__),_sha(Path(__file__).with_name('execution.py')),_sha(Path(__file__).with_name('io.py')),_sha(Path(__file__).with_name('native_pins.py'))]),
            'configuration_sha256':_sha(executor.root/'work/main.tf.json'),'saved_plan_sha256':_sha(executor.root/'work/saved.tfplan'),
            'plan_json_sha256':_sha(executor.root/'work/plan.json'),'before_state_sha256':state['state_sha256'],
            'before_value_sha256':state['value_sha256'],'before_lineage_sha256':state['lineage_sha256'],'before_serial':state['serial'],'desired_value_sha256':executor.manifest['desired_value_sha256']}


def _review_native_output_plan(document, executor, generic_review, *, bound_before=_SECRET):
    """Strict local-output slice using independently observed pre-plan state.

    OpenTofu 1.10 refresh recalculates prior_state output values. Keep the raw
    generic review diagnostic; never edit the plan to manufacture consistency.
    """
    allowed={'format_version','terraform_version','planned_values','output_changes','prior_state','configuration','timestamp','errored','resource_changes'}
    if set(document)-allowed or document.get('format_version')!='1.2' or document.get('terraform_version')!=_engine_version(executor) or document.get('errored')is not False or document.get('resource_changes',[])!=[]:_fail('native_output_plan_shape')
    planned=document.get('planned_values',{})
    if set(planned)!={'outputs','root_module'} or planned['root_module']!={} or set(planned['outputs'])!={'fixture'}:_fail('native_output_plan_shape')
    expected=load_json(executor.root/'work/main.tf.json')['output']['fixture']['value']
    state=load_json(executor.root/'work/state/terraform.tfstate')
    before=state['outputs']['fixture']['value'] if bound_before is _SECRET else bound_before
    change=document.get('output_changes',{}).get('fixture')
    if set(document.get('output_changes',{}))!={'fixture'} or type(change)is not dict or set(change)!={'actions','before','after','after_unknown','before_sensitive','after_sensitive'}:_fail('native_output_plan_shape')
    action=['no-op'] if canonical(before)==canonical(expected) else ['update']
    if change!={'actions':action,'before':before,'after':expected,'after_unknown':False,'before_sensitive':False,'after_sensitive':False}:_fail('native_output_plan_mismatch')
    if document['configuration']!={'root_module':{'outputs':{'fixture':{'expression':{'constant_value':expected}}}}}:_fail('native_configuration_mismatch')
    output=planned['outputs']['fixture']
    if set(output)!={'value','sensitive','type'} or output['sensitive']is not False or canonical(output['value'])!=canonical(expected):_fail('native_output_plan_mismatch')
    prior=document.get('prior_state',{})
    if set(prior)!={'format_version','terraform_version','values'} or prior['format_version']!='1.0' or prior['terraform_version']!=_engine_version(executor) or set(prior['values'])!={'root_module','outputs'} or prior['values']['root_module']!={} or set(prior['values']['outputs'])!={'fixture'}:_fail('native_output_plan_shape')
    # No generic blockers other than the independently explained output mismatch.
    if any(issue['code']!='prior_output_value_mismatch' for issue in generic_review['blockers']):_fail('native_output_plan_review')
    return dict(generic_review,status='no_change' if action==['no-op'] else 'changes_require_review',
                generic_review_status=generic_review['status'],assurance='native_local_output_slice_with_independent_state')


def _generic_review(document, executor):
    if executor.mode == 'native_local_opentofu_only':
        return review_local_output_plan(document, engine_version=_engine_version(executor))
    return review_plan(document)


def prepare_native_operation(executor, *, ttl_seconds=300):
    _require_executor(executor);executor._validate()
    if type(ttl_seconds)is not int or not 1<=ttl_seconds<=300:_fail('invalid_expiry')
    if (executor.root/'.operation-lock').exists() or (executor.root/'preparation.json').exists(): _fail('target_locked')
    before=_state(executor)
    _run(executor,'plan'); raw=_run(executor,'show'); document=parse_json(raw)
    if executor.mode=='native_local_opentofu_only' and document.get('terraform_version')!=_engine_version(executor):_fail('unqualified_engine_version')
    # Native omits an empty resource_changes collection for output-only plans.
    review_document=dict(document);review_document.setdefault('resource_changes',[])
    review=_generic_review(review_document,executor)
    if executor.mode=='native_local_opentofu_only':
        review=_review_native_output_plan(document,executor,review)
    if review['status']=='blocked':_fail('plan_review_blocked')
    outputs=document.get('planned_values',{}).get('outputs',{})
    if set(outputs)!={'fixture'} or digest(outputs['fixture'].get('value'))!=executor.manifest['desired_value_sha256']: _fail('plan_target_mismatch')
    if before!=_state(executor):_fail('stale_state')
    _exclusive(executor.root/'work/plan.json',raw)
    bindings=_bindings(executor);now=_now()
    request={'schema_version':VERSION,'mode':executor.mode,'action':'synthetic_saved_plan_apply' if executor.mode=='synthetic_local_process_only' else 'native_local_saved_plan_apply',
             'operation_id':uuid.uuid4().hex,'created_at':now,'expires_at':now+ttl_seconds,'bindings':bindings,'binding_sha256':digest(bindings),
             'review':{'status':review['status'],'plan_json_sha256':review['plan_json_sha256'],'generic_review_status':review.get('generic_review_status',review['status']),'generic_blockers':review['blockers']},'execution_authorized':False}
    _exclusive(executor.root/'preparation.json',canonical(request))
    return request


class _LocalGrant:
    __slots__=('request_sha256','operation_id','expires_at','consumed','seal')
    def __init__(self, request, seal):
        if seal is not _SECRET:_fail('approval_unavailable')
        self.request_sha256=digest(request);self.operation_id=request['operation_id'];self.expires_at=request['expires_at'];self.consumed=False;self.seal=seal


def _request_shape(request):
    if type(request)is not dict or set(request)!=_REQUEST_KEYS or request['schema_version']!=VERSION or request['execution_authorized'] is not False:_fail('invalid_request')
    modes={'synthetic_local_process_only':'synthetic_saved_plan_apply','native_local_opentofu_only':'native_local_saved_plan_apply'}
    if type(request['mode'])is not str or request['mode'] not in modes or request['action']!=modes[request['mode']] or type(request['operation_id'])is not str or not _ID.fullmatch(request['operation_id']):_fail('invalid_request')
    if type(request['created_at'])is not int or type(request['expires_at'])is not int or request['created_at']<0 or not 1<=request['expires_at']-request['created_at']<=300:_fail('invalid_expiry')
    bindings=request['bindings']
    if type(bindings)is not dict or set(bindings)!=_BINDING_KEYS or type(bindings['before_serial'])is not int or not 0<=bindings['before_serial']<9007199254740991:_fail('invalid_binding')
    if any(type(bindings[key])is not str or not re.fullmatch('[0-9a-f]{64}',bindings[key]) for key in _BINDING_KEYS-{'before_serial'}) or request['binding_sha256']!=digest(bindings):_fail('invalid_binding')
    review=request['review']
    if type(review)is not dict or set(review)!={'status','plan_json_sha256','generic_review_status','generic_blockers'} or review['status'] not in ('no_change','changes_require_review') or type(review['plan_json_sha256'])is not str or not re.fullmatch('[0-9a-f]{64}',review['plan_json_sha256']):_fail('invalid_review')
    if review['generic_blockers']==[]:
        if review['generic_review_status']!=review['status']:_fail('invalid_review')
    elif request['mode']!='native_local_opentofu_only' or review['generic_review_status']!='blocked' or review['generic_blockers']!=[{'code':'prior_output_value_mismatch','location':'plan'}]:_fail('invalid_review')


def _validate_request(request, executor, *, fresh=True, state=True):
    _require_executor(executor); request=_json_snapshot(request);_request_shape(request)
    if type(request)is not dict or set(request)!=_REQUEST_KEYS or request['schema_version']!=VERSION or request['mode']!=executor.mode or request['execution_authorized'] is not False:_fail('invalid_request')
    action='synthetic_saved_plan_apply' if executor.mode=='synthetic_local_process_only' else 'native_local_saved_plan_apply'
    if request['action']!=action or type(request['operation_id'])is not str or not _ID.fullmatch(request['operation_id']):_fail('invalid_request')
    if type(request['created_at'])is not int or type(request['expires_at'])is not int or not 1<=request['expires_at']-request['created_at']<=300:_fail('invalid_expiry')
    if fresh and not request['created_at']<=_now()<request['expires_at']:_fail('expired_request')
    if type(request['bindings'])is not dict or set(request['bindings'])!=_BINDING_KEYS or request['binding_sha256']!=digest(request['bindings']):_fail('invalid_binding')
    if request!=load_json(_path(executor.root/'preparation.json')):_fail('request_changed')
    executor._validate();actual=_bindings(executor)
    ignored=set() if state else {'before_state_sha256','before_value_sha256','before_lineage_sha256','before_serial'}
    if any(actual[k]!=request['bindings'][k] for k in _BINDING_KEYS-ignored):_fail('evidence_changed')
    if executor.mode=='native_local_opentofu_only':
        # Re-derive from the exact native binary, not a mutable JSON sidecar.
        raw=_run(executor,'show')
        if hashlib.sha256(raw).hexdigest()!=request['bindings']['plan_json_sha256']:_fail('binary_plan_json_mismatch')
    else:
        saved=_json_snapshot(load_json(executor.root/'work/saved.tfplan'))
        if type(saved)is not dict or set(saved)!={'schema','before_sha256','value'} or saved['schema']!='synthetic-saved-plan/1' or saved['before_sha256']!=request['bindings']['before_state_sha256'] or digest(saved['value'])!=request['bindings']['desired_value_sha256']:_fail('synthetic_saved_plan_mismatch')
    document=load_json(executor.root/'work/plan.json')
    if executor.mode=='synthetic_local_process_only':
        change=document.get('output_changes',{}).get('fixture',{})
        expected_action=['no-op'] if request['bindings']['before_value_sha256']==request['bindings']['desired_value_sha256'] else ['update']
        if document.get('resource_changes')!=[] or document.get('configuration')!={} or set(document.get('output_changes',{}))!={'fixture'} or digest(change.get('before'))!=request['bindings']['before_value_sha256'] or digest(change.get('after'))!=request['bindings']['desired_value_sha256'] or change.get('actions')!=expected_action:_fail('synthetic_plan_semantics_mismatch')
    normalized=dict(document);normalized.setdefault('resource_changes',[])
    reviewed=_generic_review(normalized,executor)
    if executor.mode=='native_local_opentofu_only':
        before=document.get('output_changes',{}).get('fixture',{}).get('before')
        if digest(before)!=request['bindings']['before_value_sha256']:_fail('review_binding_changed')
        reviewed=_review_native_output_plan(document,executor,reviewed,bound_before=before)
    summary={'status':reviewed['status'],'plan_json_sha256':reviewed['plan_json_sha256'],
             'generic_review_status':reviewed.get('generic_review_status',reviewed['status']),'generic_blockers':reviewed['blockers']}
    if request['review']!=summary:_fail('review_binding_changed')
    return request


def validate_native_operation(request, *, executor, require_fresh=False, require_state=False):
    checked=_validate_request(request,executor,fresh=require_fresh,state=require_state)
    return {'status':'valid','binding_sha256':checked['binding_sha256'],'execution_authorized':False}


def approve_synthetic_operation(request, *, executor):
    if type(executor)is not SyntheticExecutor:_fail('wrong_approval_mode')
    if (executor.root/'consumed.json').exists():_fail('approval_already_consumed')
    return _LocalGrant(_validate_request(request,executor),_SECRET)


def approve_native_local_operation(request, *, executor):
    """Explicit local-test approval only; there is no cloud approval constructor."""
    if type(executor)is not NativeLocalExecutor:_fail('wrong_approval_mode')
    if (executor.root/'consumed.json').exists():_fail('approval_already_consumed')
    return _LocalGrant(_validate_request(request,executor),_SECRET)


def _event(root, kind, payload):
    index=_EVENT_KINDS.index(kind)
    previous='0'*64 if index==0 else _sha(root/f'{index-1:02d}.json')
    value={'schema_version':VERSION,'sequence':index,'kind':kind,'previous_sha256':previous,'payload':payload}
    _exclusive(root/f'{index:02d}.json',canonical(value));return _sha(root/f'{index:02d}.json')


def _owner(lock, expected):
    if load_json(_path(lock/'owner.json'))!=expected:_fail('ownership_lost')


def _desired_readback(request, observed):
    binding=request['bindings']
    if observed['value_sha256']!=binding['desired_value_sha256'] or observed['lineage_sha256']!=binding['before_lineage_sha256'] or type(observed['serial'])is not int:return False
    changed=binding['before_value_sha256']!=binding['desired_value_sha256']
    serials={binding['before_serial']+1} if changed else {binding['before_serial'],binding['before_serial']+1}
    return observed['serial'] in serials and (observed['serial']!=binding['before_serial'] or observed['state_sha256']==binding['before_state_sha256'])


def execute_native_operation(request, state_dir, *, executor, approval):
    result={'status':'rejected','execution_authorized':False,'assurance':'local_execution_only'}
    lock=None; dispatched=False
    try:
        request=_validate_request(request,executor)
        if (executor.root/'consumed.json').exists():_fail('approval_already_consumed')
        result.update(operation_id=request['operation_id'],assurance=executor.mode)
        if type(approval)is not _LocalGrant or approval.seal is not _SECRET or approval.consumed or approval.request_sha256!=digest(request) or approval.expires_at<=_now():_fail('approval_required')
        directory=_path(state_dir)
        if directory==executor.root or executor.root in directory.parents or directory in executor.root.parents:_fail('overlapping_paths')
        directory.mkdir(mode=0o700,parents=True,exist_ok=True)
        lock=executor.root/'.operation-lock';lock.mkdir(mode=0o700);_sync(executor.root)
        owner={'operation_id':request['operation_id'],'request_sha256':digest(request),'receipt_root_sha256':digest(str(directory))}
        _exclusive(lock/'owner.json',canonical(owner))
        journal=directory/request['operation_id'];journal.mkdir(mode=0o700);_sync(directory)
        _event(journal,'prepared',{'request':request})
        approval.consumed=True
        _exclusive(executor.root/'consumed.json',canonical({'operation_id':request['operation_id'],'request_sha256':digest(request),'action':request['action']}))
        _event(journal,'authorized',{'request_sha256':digest(request),'scope':'local_fixture_only'})
        _validate_request(request,executor);_owner(lock,owner)
        _event(journal,'dispatch_started',{'binding_sha256':request['binding_sha256']})
        # A persisted started event is an uncertainty boundary even if dispatch fails.
        dispatched=True
        _validate_request(request,executor);_owner(lock,owner)
        _run(executor,'apply')
        _owner(lock,owner);_validate_request(request,executor,fresh=False,state=False)
        observed=_state(executor)
        if not _desired_readback(request,observed):_fail('readback_mismatch')
        _event(journal,'readback_verified',observed)
        receipt_sha=_event(journal,'completed',{'outcome':'succeeded_verified','request_sha256':digest(request)})
        receipt=read_native_operation(request['operation_id'],directory)
        if receipt['status']!='succeeded_verified' or receipt['receipt_sha256']!=receipt_sha:_fail('receipt_unverified')
        _owner(lock,owner);(lock/'owner.json').unlink();lock.rmdir();_sync(executor.root)
        result.update(status='succeeded_verified',receipt_sha256=receipt_sha)
    except Exception as exc:
        result.update(status='outcome_unknown' if dispatched else 'rejected',error={'code':getattr(exc,'code','protected_operation_failed')})
    return result


def read_native_operation(operation_id, state_dir):
    unknown={'status':'unknown','execution_authorized':False,'events':[]}
    try:
        if type(operation_id)is not str or not _ID.fullmatch(operation_id):return unknown
        root=_path(state_dir)/operation_id
        paths=[]
        for index,path in enumerate(root.iterdir()):
            if index>=5:return unknown
            paths.append(path)
        paths.sort()
        if not paths or len(paths)>5 or [p.name for p in paths]!=[f'{i:02d}.json' for i in range(len(paths))]:return unknown
        previous='0'*64;events=[];request=None
        for index,path in enumerate(paths):
            value=load_json(_path(path))
            if type(value)is not dict or set(value)!={'schema_version','sequence','kind','previous_sha256','payload'} or value['schema_version']!=VERSION or type(value['sequence'])is not int or value['sequence']!=index or value['kind']!=_EVENT_KINDS[index] or value['previous_sha256']!=previous:return unknown
            payload=value['payload']
            if index==0:
                if type(payload)is not dict or set(payload)!={'request'}:return unknown
                request=payload['request'];_request_shape(request)
                if type(request)is not dict or set(request)!=_REQUEST_KEYS or request['operation_id']!=operation_id or request['binding_sha256']!=digest(request['bindings']):return unknown
            elif index==1:
                if payload!={'request_sha256':digest(request),'scope':'local_fixture_only'}:return unknown
            elif index==2:
                if payload!={'binding_sha256':request['binding_sha256']}:return unknown
            elif index==3:
                if type(payload)is not dict or set(payload)!={'state_sha256','value_sha256','serial','lineage_sha256'} or not _desired_readback(request,payload) or not re.fullmatch('[0-9a-f]{64}',payload['state_sha256']):return unknown
            elif payload!={'outcome':'succeeded_verified','request_sha256':digest(request)}:return unknown
            events.append(value);previous=_sha(path)
        return {'status':'succeeded_verified' if len(events)==5 else 'outcome_unknown','execution_authorized':False,'request':request,'events':events,'receipt_sha256':previous}
    except Exception:return unknown


def reconcile_native_operation(operation_id, state_dir, *, executor):
    result={'classification':'unknown','replay_authorized':False,'execution_authorized':False}
    try:
        history=read_native_operation(operation_id,state_dir)
        if 'request' not in history:return result
        request=_validate_request(history['request'],executor,fresh=False,state=False)
        state=_state(executor)
        classification='desired_state_observed' if _desired_readback(request,state) else 'matches_precondition' if state['state_sha256']==request['bindings']['before_state_sha256'] else 'diverged'
        result.update(classification=classification,state_sha256=state['state_sha256'],value_sha256=state['value_sha256'])
    except Exception:pass
    return result


def _convergence_report(executor, request):
    """Re-derive a local no-change assertion from native plan bytes and state.

    This proves output-only convergence, never that an approved apply occurred.
    Callers must separately reconstruct the operation's execution journal.
    """
    if type(executor)is not NativeLocalExecutor:_fail('wrong_executor_mode')
    request=_validate_request(request,executor,fresh=False,state=False)
    before=_state(executor)
    if not _desired_readback(request,before):_fail('readback_mismatch')
    plan_path=executor.root/'work/second.tfplan'
    plan_sha=_sha(plan_path)
    raw=_run(executor,'second_show')
    if read_bytes(executor.root/'work/second-plan.json')!=raw:_fail('second_plan_json_mismatch')
    document=parse_json(raw);normalized=dict(document);normalized.setdefault('resource_changes',[])
    review=_review_native_output_plan(document,executor,_generic_review(normalized,executor))
    if review['status']!='no_change':_fail('second_plan_has_changes')
    _validate_request(request,executor,fresh=False,state=False)
    after=_state(executor)
    if before!=after or _sha(plan_path)!=plan_sha:_fail('convergence_evidence_changed')
    return {'schema_version':'native-local-convergence/1','status':'verified','changes':[],
            'scope':'native_local_output_only','execution_authorized':False,
            'request_sha256':digest(request),'before_state_sha256':before['state_sha256'],
            'after_state_sha256':after['state_sha256'],'lineage_sha256':after['lineage_sha256'],
            'serial':after['serial'],'value_sha256':after['value_sha256'],
            'approved_saved_plan_sha256':request['bindings']['saved_plan_sha256'],
            'second_plan_sha256':plan_sha,'second_plan_json_sha256':hashlib.sha256(raw).hexdigest()}


def reconstruct_native_convergence(executor, request, report):
    """Validate persisted evidence with native show; never run plan or apply."""
    reconstructed=_convergence_report(executor,request)
    # Python mapping equality equates False with 0 and integers with floats.
    # Durable typed evidence must match JSON semantics, not those coercions.
    if type(report)is not dict or canonical(_json_snapshot(report))!=canonical(reconstructed):_fail('convergence_report_changed')
    return reconstructed


def verify_native_convergence(executor, request):
    """Save a distinct second plan; retain the exact approved original.

    Existing second-plan artifacts are inspected and never overwritten. An
    interrupted successful plan can be completed with its independently derived
    JSON; an incomplete or divergent artifact remains visible and fails closed.
    """
    if type(executor)is not NativeLocalExecutor:_fail('wrong_executor_mode')
    request=_validate_request(request,executor,fresh=False,state=False)
    before=_state(executor)
    if not _desired_readback(request,before):_fail('readback_mismatch')
    lock=executor.root/'.convergence-lock';owner=canonical({'request_sha256':digest(request),'token':uuid.uuid4().hex})
    try:_exclusive(lock,owner)
    except FileExistsError:_fail('target_locked')
    try:
        work=executor.root/'work';plan=work/'second.tfplan';sidecar=work/'second-plan.json'
        if not plan.exists():
            if sidecar.exists():_fail('incomplete_convergence_evidence')
            _run(executor,'second_plan')
            fd=os.open(_path(plan),os.O_RDONLY|getattr(os,'O_NOFOLLOW',0))
            try:os.fsync(fd)
            finally:os.close(fd)
            _sync(work)
        raw=_run(executor,'second_show')
        if not sidecar.exists():_exclusive(sidecar,raw)
        report=_convergence_report(executor,request)
        if before!=_state(executor):_fail('convergence_evidence_changed')
        return report
    finally:
        if read_bytes(lock)!=owner:_fail('ownership_lost')
        lock.unlink();_sync(executor.root)
